// <auto-generated />
using FoodSense.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodSense.API.Migrations
{
    [DbContext(typeof(FoodSenseDbContext))]
    [Migration("20260729150556_AddBarcodeUniqueness")]
    partial class AddBarcodeUniqueness
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodSense.API.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("AdditivesDebugTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AdditivesN")
                        .HasColumnType("int");

                    b.Property<int?>("AdditivesOldN")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("AdditivesOldTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("AdditivesOriginalTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("AdditivesPrevOriginalTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("AdditivesTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AllergensFromIngredients")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AllergensFromUser")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("AllergensHierarchy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AllergensLc")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("AllergensTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("AminoAcidsPrevTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("AminoAcidsTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brands")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("BrandsDebugTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("BrandsTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarbonFootprintFromKnownIngredientsDebug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarbonFootprintPercentOfKnownIngredients")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("CategoriesHierarchy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoriesLc")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("CategoriesPropertiesTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("CategoriesTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("CheckersTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("CitiesTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("CodesTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComparedToCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CompletedT")
                        .HasColumnType("bigint");

                    b.Property<string>("ConservationConditions")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("CorrectorsTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("CountriesDebugTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("CountriesHierarchy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountriesLc")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("CountriesTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CreatedT")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<string>("DataQualityBugsTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("DataQualityErrorsTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("DataQualityInfoTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("DataQualityTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("DataQualityWarningsTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataSources")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("DataSourcesTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("DebugParamSortedLangs")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("EditorsTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbCodes")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("EmbCodesDebugTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbCodesOrig")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("EmbCodesTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("EntryDatesTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpirationDate")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ExpirationDateDebugTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FruitsVegetablesNuts100GEstimate")
                        .HasColumnType("int");

                    b.Property<string>("GenericName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFrontSmallUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFrontThumbUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFrontUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageIngredientsSmallUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageIngredientsThumbUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageIngredientsUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageNutritionSmallUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageNutritionThumbUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageNutritionUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageSmallUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThumbUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("InformersTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("IngredientsAnalysisTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("IngredientsDebug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IngredientsFromOrThatMayBeFromPalmOilN")
                        .HasColumnType("int");

                    b.Property<int?>("IngredientsFromPalmOilN")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("IngredientsFromPalmOilTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("IngredientsHierarchy")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("IngredientsIdsDebug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IngredientsN")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("IngredientsNTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("IngredientsOriginalTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("IngredientsTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IngredientsText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IngredientsTextDebug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IngredientsTextWithAllergens")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IngredientsThatMayBeFromPalmOilN")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("IngredientsThatMayBeFromPalmOilTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterfaceVersionCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterfaceVersionModified")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Keywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KnownIngredientsN")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("LabelsDebugTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("LabelsHierarchy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabelsLc")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("LabelsPrevHierarchy")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("LabelsPrevTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("LabelsTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("LangDebugTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguagesCodesEn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LanguagesCodesFr")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LanguagesCodesPl")
                        .HasColumnType("nvarchar(450)");

                    b.PrimitiveCollection<string>("LanguagesHierarchy")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("LanguagesTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("LastEditDatesTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastEditor")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("LastImageDatesTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("LastImageT")
                        .HasColumnType("bigint");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("LastModifiedT")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<string>("LinkDebugTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturingPlaces")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ManufacturingPlacesDebugTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ManufacturingPlacesTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaxImgid")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("MineralsPrevTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("MineralsTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("MiscTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetWeightUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetWeightValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoNutritionData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NovaGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NovaGroupDebug")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("NovaGroupTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NovaGroups")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("NovaGroupsTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("NucleotidesPrevTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("NucleotidesTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NutrientLevelsFat")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NutrientLevelsSalt")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NutrientLevelsSaturatedFat")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NutrientLevelsSugars")
                        .HasColumnType("nvarchar(450)");

                    b.PrimitiveCollection<string>("NutrientLevelsTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NutritionData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NutritionDataPer")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("NutritionDataPerDebugTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NutritionDataPrepared")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NutritionDataPreparedPer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NutritionGrades")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("NutritionGradesTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NutritionScoreBeverage")
                        .HasColumnType("int");

                    b.Property<string>("NutritionScoreDebug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NutritionScoreWarningNoFiber")
                        .HasColumnType("int");

                    b.Property<int?>("NutritionScoreWarningNoFruitsVegetablesNuts")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("OriginsDebugTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("OriginsTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherInformation")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("OtherNutritionalSubstancesTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("PackagingDebugTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("PackagingTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("PhotographersTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PnnsGroups1")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("PnnsGroups1Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PnnsGroups2")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("PnnsGroups2Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PopularityKey")
                        .HasColumnType("bigint");

                    b.Property<string>("ProducerVersionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductQuantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchasePlaces")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("PurchasePlacesDebugTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("PurchasePlacesTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("QualityTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("QuantityDebugTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecyclingInstructionsToDiscard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServingQuantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServingSize")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ServingSizeDebugTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("StatesHierarchy")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("StatesTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("StoresDebugTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("StoresTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("TracesDebugTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TracesFromIngredients")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TracesFromUser")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("TracesHierarchy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TracesLc")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("TracesTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UnknownIngredientsN")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("UnknownNutrientsTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateKey")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("VitaminsPrevTags")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("VitaminsTags")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguagesCodesEn", "LanguagesCodesFr", "LanguagesCodesPl");

                    b.HasIndex("NutrientLevelsSalt", "NutrientLevelsSugars", "NutrientLevelsSaturatedFat", "NutrientLevelsFat");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("OpenFoodFactsCSharp.Models.LanguagesCodes", b =>
                {
                    b.Property<string>("En")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Fr")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Pl")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("En", "Fr", "Pl");

                    b.ToTable("LanguagesCodes");
                });

            modelBuilder.Entity("OpenFoodFactsCSharp.Models.NutrientLevels", b =>
                {
                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sugars")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SaturatedFat")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Fat")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Salt", "Sugars", "SaturatedFat", "Fat");

                    b.ToTable("NutrientLevels");
                });

            modelBuilder.Entity("FoodSense.API.Data.Models.Product", b =>
                {
                    b.HasOne("OpenFoodFactsCSharp.Models.LanguagesCodes", "LanguagesCodes")
                        .WithMany()
                        .HasForeignKey("LanguagesCodesEn", "LanguagesCodesFr", "LanguagesCodesPl");

                    b.HasOne("OpenFoodFactsCSharp.Models.NutrientLevels", "NutrientLevels")
                        .WithMany()
                        .HasForeignKey("NutrientLevelsSalt", "NutrientLevelsSugars", "NutrientLevelsSaturatedFat", "NutrientLevelsFat");

                    b.Navigation("LanguagesCodes");

                    b.Navigation("NutrientLevels");
                });
#pragma warning restore 612, 618
        }
    }
}
